version: '3'

services:
  dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_URL=redis://cache
    ports:
      - 3000:3000
