version: '3'

services:
  proxy:
    image: nginx:1.15.11-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    ports:
      - 8080:80
