version: '3'

services:
  client:
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: Host:${DOMAIN:-cohesion.localhost}
    networks:
      - default
      - web
  server:
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: Host:${DOMAIN:-cohesion.localhost};PathPrefixStrip:/api
    networks:
      - default
      - web

networks:
  web:
    external: true
