version: '3'

services:
  client:
    image: dacio/cohesion-client:1.1.0
    depends_on:
      - server
  server:
    image: dacio/cohesion-server:1.2.0
    depends_on:
      - cache
    env_file: server.env
    environment:
      - REDIS_URL=redis://cache
  cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./data/db:/data/db
