version: '3'
services:
  client:
    image: registry.gitlab.com/cohesion-app/client
    ports:
      - '${PORT:-3000}:80'
    depends_on:
      - server
    environment:
      - PROXY_URL=http://server:80
  server:
    image: registry.gitlab.com/cohesion-app/server
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
      - PORT=80
      - STEAM_API_KEY
      - IGDB_API_KEY
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data/db
