version: '3'

services:
  client:
    build: ./services/client
    depends_on:
      - server
  server:
    build: ./services/server
    depends_on:
      - cache
    env_file: server.env
    environment:
      - REDIS_URL=redis://cache
  cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./data/db:/data/db
