version: '3'

services:
  client:
    image: dacio/cohesion-client:1.1.0
    depends_on:
      - server
    env_file: client.env
  server:
    image: dacio/cohesion-server:1.2.0
    depends_on:
      - redis
    env_file: server.env
    environment:
      - REDIS_URL=redis://redis
  redis:
    image: redis:5.0.4-alpine
    volumes:
      - cache:/data/db

volumes:
  cache:
