version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./services/client/Dockerfile
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
    depends_on:
      - cache
    env_file: ./services/server/.env
    environment:
      - REDIS_URL=redis://cache
  cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./data/db:/data/db
