version: '3'
services:
  client:
    image: registry.gitlab.com/cohesion-app/client
    depends_on:
      - server
  server:
    image: registry.gitlab.com/cohesion-app/server
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
      - STEAM_API_KEY
      - IGDB_API_KEY
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data/db
