version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./services/client/Dockerfile
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
    depends_on:
      - cache
    env_file: ./services/server/.env
    environment:
      - REDIS_URL=redis://cache
  proxy:
    image: nginx:1.15.11-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    ports:
      - 8080:80
