version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:80"
    depends_on:
      - cache
    env_file: .env
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./controllers:/usr/src/app/controllers
      - ./utils:/usr/src/app/utils
  cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./data:/data
