version: '3'
services:
  web:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - redis
    environment:
      - STEAM_API_KEY
      - IGDB_API_KEY
      - REDIS_URL=redis://redis
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
